<?xml version="1.0" encoding="utf-8"?><Database Name="clinicasCR" Class="ReporteDatosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=clinicasCR;Integrated Security=True" SettingsObjectName="ControlSeguridadBD.Properties.Settings" SettingsPropertyName="clinicasCRConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.bitacora" Member="bitacoras">
    <Type Name="bitacora">
      <Column Name="idTransaccion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tipoProceso" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="servidor" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="baseDatos" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="tabla" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="regAnterior" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="regNuevo" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="usuario" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="aplicacion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="equipo" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="fechaMov" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>