#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlSeguridadBD
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="clinicasCR")]
	public partial class ReporteDatosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ReporteDatosDataContext() : 
				base(global::ControlSeguridadBD.Properties.Settings.Default.clinicasCRConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ReporteDatosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReporteDatosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReporteDatosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReporteDatosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<bitacora> bitacoras
		{
			get
			{
				return this.GetTable<bitacora>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bitacora")]
	public partial class bitacora
	{
		
		private int _idTransaccion;
		
		private char _tipoProceso;
		
		private string _servidor;
		
		private string _baseDatos;
		
		private string _tabla;
		
		private string _regAnterior;
		
		private string _regNuevo;
		
		private string _usuario;
		
		private string _aplicacion;
		
		private string _equipo;
		
		private System.DateTime _fechaMov;
		
		public bitacora()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTransaccion", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int idTransaccion
		{
			get
			{
				return this._idTransaccion;
			}
			set
			{
				if ((this._idTransaccion != value))
				{
					this._idTransaccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoProceso", DbType="Char(1) NOT NULL")]
		public char tipoProceso
		{
			get
			{
				return this._tipoProceso;
			}
			set
			{
				if ((this._tipoProceso != value))
				{
					this._tipoProceso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_servidor", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string servidor
		{
			get
			{
				return this._servidor;
			}
			set
			{
				if ((this._servidor != value))
				{
					this._servidor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_baseDatos", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string baseDatos
		{
			get
			{
				return this._baseDatos;
			}
			set
			{
				if ((this._baseDatos != value))
				{
					this._baseDatos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tabla", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string tabla
		{
			get
			{
				return this._tabla;
			}
			set
			{
				if ((this._tabla != value))
				{
					this._tabla = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_regAnterior", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string regAnterior
		{
			get
			{
				return this._regAnterior;
			}
			set
			{
				if ((this._regAnterior != value))
				{
					this._regAnterior = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_regNuevo", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string regNuevo
		{
			get
			{
				return this._regNuevo;
			}
			set
			{
				if ((this._regNuevo != value))
				{
					this._regNuevo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this._usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aplicacion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string aplicacion
		{
			get
			{
				return this._aplicacion;
			}
			set
			{
				if ((this._aplicacion != value))
				{
					this._aplicacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equipo", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string equipo
		{
			get
			{
				return this._equipo;
			}
			set
			{
				if ((this._equipo != value))
				{
					this._equipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaMov", DbType="DateTime NOT NULL")]
		public System.DateTime fechaMov
		{
			get
			{
				return this._fechaMov;
			}
			set
			{
				if ((this._fechaMov != value))
				{
					this._fechaMov = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
